import { afterEach, beforeEach, expect, it, vi } from 'vitest'
import { flushPromises, mount } from '@vue/test-utils'
import { reactive, defineComponent, h } from 'vue'
import SqlProvenanceDrawer from '../../app/components/sql/SqlProvenanceDrawer.vue'
import SqlProvenanceButton from '../../app/components/sql/SqlProvenanceButton.vue'
import fixtures from '../fixtures/sql-provenance.json'
import { provenanceDefinitionSchema, provenanceResultSchema } from '../../shared/sql-provenance'
import { AdminApiError, failure } from '../../shared/errors'
import { forwardAdminRequest } from '../../server/utils/admin-proxy'
import { createAdminApi } from '../../app/utils/admin-api'
import { findings } from '../fixtures/api'
import { filtersSchema } from '../../shared/contracts'

const definition = provenanceDefinitionSchema.parse(fixtures.dashboard)
const source = definition.sources[0]!
const result = {
  source_id: source.id,
  datasource: source.datasource,
  columns: ['kind', 'count'],
  rows: [{ kind: 'venue', count: 7 }],
  row_count: 1,
  duration_ms: 2,
  observed_at: definition.observed_at,
  truncated: false,
}
const api = {
  provenance: vi.fn(),
  executeProvenance: vi.fn(),
  viewRead: vi.fn(),
  subscribeViewReads: vi.fn(),
}
const modal = defineComponent({
  setup(_, { slots, expose }) {
    expose({ open: vi.fn(), close: vi.fn() })
    return () => h('div', slots.default?.())
  },
})
const stubs = { AppModal: modal, SqlProvenanceButton: false }
beforeEach(() => {
  vi.stubGlobal('useNuxtApp', () => ({ $adminApi: api }))
  api.provenance.mockReset().mockResolvedValue(definition)
  api.executeProvenance.mockReset().mockResolvedValue(result)
  api.viewRead.mockReset()
  api.subscribeViewReads.mockReset().mockReturnValue(() => {})
})
afterEach(() => vi.unstubAllGlobals())

it('validates definitions generated by the backend registry', () => {
  for (const fixture of Object.values(fixtures))
    expect(provenanceDefinitionSchema.safeParse(fixture).success).toBe(true)
})
it('loads only on demand, copies a query and isolates source results and errors', async () => {
  const writeText = vi.fn().mockResolvedValue(undefined)
  Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText } })
  const view = mount(SqlProvenanceDrawer, {
    props: { view: 'dashboard', parameters: { period: '24h' } },
    global: { stubs },
  })
  expect(api.provenance).not.toHaveBeenCalled()
  await view.vm.open()
  await flushPromises()
  expect(api.provenance).toHaveBeenCalledExactlyOnceWith('dashboard', { period: '24h' })
  expect(api.executeProvenance).not.toHaveBeenCalled()
  expect(view.text()).toContain('Uranus · READ ONLY')
  expect(view.text()).toContain('Admin · READ ONLY')
  const panels = view.findAll('section').filter((item) => item.find('code').exists())
  await panels[0]!.findAll('button')[0]!.trigger('click')
  await flushPromises()
  expect(writeText).toHaveBeenCalledExactlyOnceWith(source.copy_sql)
  await panels[0]!.findAll('button')[1]!.trigger('click')
  await flushPromises()
  expect(api.executeProvenance).toHaveBeenCalledExactlyOnceWith(
    'dashboard',
    source.id,
    definition.parameters,
  )
  expect(panels[0]!.get('table').text()).toContain('venue')
  api.executeProvenance.mockRejectedValue(new AdminApiError(failure(504, 'diagnostic_timeout')))
  await panels[1]!.findAll('button')[1]!.trigger('click')
  await flushPromises()
  expect(panels[1]!.get('[role="alert"]').text()).toContain('Zeitlimit')
  expect(panels[0]!.get('table').text()).toContain('venue')
  view.unmount()
})
it('discards a late definition after close', async () => {
  let finish: (value: unknown) => void = () => {}
  api.provenance.mockReturnValue(
    new Promise((resolve) => {
      finish = resolve
    }),
  )
  const view = mount(SqlProvenanceDrawer, {
    props: { view: 'dashboard', parameters: {} },
    global: { stubs },
  })
  const pending = view.vm.open()
  await flushPromises()
  expect(view.text()).toContain('Datenherkunft laden')
  view.vm.close()
  finish(definition)
  await pending
  await flushPromises()
  expect(view.find('code').exists()).toBe(false)
  view.unmount()
})
it('uses the actual successful filtered request and invalidates the drawer on changes', async () => {
  const route = reactive({
    path: '/findings',
    fullPath: '/findings?severity=error&active_only=true',
    query: {},
    params: {},
  })
  vi.stubGlobal('useRoute', () => route)
  let notify = () => {}
  api.subscribeViewReads.mockImplementation((callback: () => void) => {
    notify = callback
    return () => {}
  })
  api.viewRead.mockReturnValue({
    query: { severity: 'error', active_only: true, page: 1 },
    pending: false,
    revision: 1,
  })
  const view = mount(SqlProvenanceButton, { global: { stubs } })
  await view.get('button').trigger('click')
  await flushPromises()
  expect(api.provenance).toHaveBeenCalledWith('findings', {
    severity: 'error',
    active_only: true,
    page: 1,
  })
  api.viewRead.mockReturnValue({
    query: { severity: 'warning', active_only: true },
    pending: true,
    revision: 2,
  })
  notify()
  await flushPromises()
  expect(view.get('button').attributes('disabled')).toBeDefined()
  expect(view.find('code').exists()).toBe(false)
  view.unmount()
})
it('rejects secrets and opaque payloads before rendering', () => {
  for (const column of ['accept_token', 'password_hash', 'metadata', 'payload', 'session_token'])
    expect(
      provenanceResultSchema.safeParse({
        ...result,
        columns: [column],
        rows: [{ [column]: 'TOP-SECRET' }],
      }).success,
    ).toBe(false)
})
it('captures request filters without extra network calls and clears on auth loss', async () => {
  const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify(findings)))
  const client = createAdminApi(fetcher)
  await client.findings(filtersSchema.parse({ severity: 'error', active_only: true }))
  expect(fetcher).toHaveBeenCalledTimes(1)
  expect(client.viewRead('/api/v1/findings')?.query).toMatchObject({
    severity: 'error',
    active_only: true,
  })
  client.clearCredential()
  expect(client.viewRead('/api/v1/findings')).toBeUndefined()
})
it('proxy only forwards registered view/source IDs and allowed parameter keys', async () => {
  const fetcher = vi.fn().mockResolvedValue(new Response(JSON.stringify(result)))
  const base = 'http://127.0.0.1:8000'
  const input = {
    path: '/api/v1/sql-provenance/dashboard/dashboard.new_records/execute',
    method: 'POST',
    query: new URLSearchParams(),
    authorization: 'Bearer fixture',
    body: { period: '24h' },
  }
  expect((await forwardAdminRequest(input, base, fetcher)).status).toBe(200)
  for (const key of ['sql', 'table', 'column', 'limit'])
    expect(
      (
        await forwardAdminRequest(
          { ...input, body: { ...input.body, [key]: 'forbidden' } },
          base,
          fetcher,
        )
      ).status,
    ).toBe(422)
  expect(
    (
      await forwardAdminRequest(
        { ...input, path: input.path.replace('dashboard.new_records', 'checks.records') },
        base,
        fetcher,
      )
    ).status,
  ).toBe(404)
  expect(
    (await forwardAdminRequest({ ...input, method: 'GET', body: undefined }, base, fetcher)).status,
  ).toBe(405)
  expect(
    (
      await forwardAdminRequest(
        {
          ...input,
          path: '/api/v1/sql-provenance/dashboard',
          method: 'GET',
          body: undefined,
          query: new URLSearchParams('period=24h&period=7d'),
        },
        base,
        fetcher,
      )
    ).status,
  ).toBe(422)
  expect(fetcher).toHaveBeenCalledTimes(1)
})

it('captures the actual dashboard live mode instead of assuming persisted data', async () => {
  const { summary } = await import('../fixtures/api')
  const client = createAdminApi(
    vi
      .fn()
      .mockResolvedValue(
        new Response(JSON.stringify({ ...summary, quality: { ...summary.quality, mode: 'live' } })),
      ),
  )
  await client.summary('24h')
  expect(client.viewRead('/api/v1/dashboard/summary')?.dataMode).toBe('live')
})
