"""One HTML structure, escaped source values and complete plain text."""

import re
from html import escape
from urllib.parse import urlsplit
from uuid import UUID

from app.config import Settings
from app.schemas.notifications import NotificationPayload, NotificationPreview
from app.services.notifications.localization import catalogue, format_date
from app.services.notifications.policy import EXTERNAL_POLICY


def safe_subject(value: str) -> str:
    return " ".join(re.sub(r"[\x00-\x1f\x7f]", " ", value).split())[:180]


def action_url(base: str, path: str) -> str:
    # Paths are generated by the application, but validate snapshots defensively too.
    parsed = urlsplit(path)
    if (
        parsed.scheme
        or parsed.netloc
        or not path.startswith("/")
        or path.startswith("//")
        or "\\" in path
    ):
        raise ValueError("Invalid action path")
    return base + path


def render(
    payloads: list[NotificationPayload],
    requested: str,
    settings: Settings,
    ids: list[UUID] | None = None,
) -> NotificationPreview:
    if not payloads:
        raise ValueError("Empty email")
    locale, t = catalogue(requested)
    quality = payloads[0].rule is not None
    if any((p.rule is not None) != quality for p in payloads):
        raise ValueError("Mixed notification families")
    ranks = {"urgent": 0, "important": 1, "improvement": 2, "internal": 3}
    group_rank: dict[tuple[str, str], int] = {}
    for p in payloads:
        key = (p.entity_type, p.entity_key)
        group_rank[key] = min(group_rank.get(key, 3), ranks[p.priority])
    payloads = sorted(
        payloads,
        key=lambda p: (
            group_rank[(p.entity_type, p.entity_key)],
            p.entity_type,
            p.entity_name,
            p.entity_key,
            p.rule or "",
        ),
    )
    if quality:
        subject = t["quality_one" if len(payloads) == 1 else "quality_many"].format(
            count=len(payloads)
        )
    else:
        title = payloads[0].entity_name
        title = title if len(title) <= 90 else title[:87] + "…"
        subject = t["single" if len(payloads) == 1 else "multiple"].format(
            title=title, count=len(payloads)
        )
    plain = [t["hello"]]
    parts = [f"<p>{escape(t['hello'])}</p>"]

    def paragraph(value: str) -> None:
        plain.append(value)
        parts.append(f"<p>{escape(value)}</p>")

    previous = None
    for p in payloads:
        group = (p.entity_type, p.entity_key)
        if group != previous:
            heading = f"{p.entity_name} · {t[p.entity_type]}"
            plain.append(heading)
            parts.append(f"<h2>{escape(heading)}</h2>")
            previous = group
        if p.priority in {"urgent", "important"}:
            paragraph(t[p.priority])
        if quality:
            policy = EXTERNAL_POLICY.get(p.rule or "")
            if policy is None or p.entity_type not in policy.entities:
                raise ValueError("Internal finding cannot be rendered externally")
            title = t[f"{policy.template}.title"]
            if p.rule == "url_syntax":
                title = t["link_title"].format(field=t.get(p.field or "", t["url"]))
            paragraph(title)
            paragraph(t[f"{policy.template}.explanation"].format(name=p.entity_name))
            paragraph(t[f"{policy.template}.recommendation"])
        else:
            if p.next_date is None or p.days_until is None or p.event_status is None:
                raise ValueError("Incomplete event snapshot")
            paragraph(
                t["intro"].format(
                    title=p.entity_name,
                    date=format_date(p.next_date, locale),
                    status=t[p.event_status],
                )
            )
            paragraph(
                t[
                    "today" if p.days_until == 0 else "tomorrow" if p.days_until == 1 else "days"
                ].format(count=p.days_until)
            )
            paragraph(t["publish"])
        url = action_url(settings.admin_public_base_url, p.action_path)
        label = t["quality_action" if quality else "event_action"]
        plain.append(f"{label}: {url}")
        parts.append(f'<p><a href="{escape(url, quote=True)}">{escape(label)}</a></p>')
    if not quality:
        paragraph(t["intentional"])
    paragraph(t["footer"].format(organization=payloads[0].organization_name))
    return NotificationPreview(
        subject=safe_subject(subject),
        text="\n\n".join(plain),
        html=f'<!doctype html><html lang="{locale}"><head><meta charset="utf-8"></head><body>'
        + "".join(parts)
        + "</body></html>",
        locale=locale,
        notification_ids=ids or [],
        delivery_enabled=settings.notifications_delivery_enabled,
    )
